### ISSUE TITLE
TUI Improvements

### ISSUE THREAD

**Issue by thw26** [FaithLife-Community/LogosLinuxInstaller#42]
- [x] Add Curses file selector in place of curses_get_user_input() for file selections. See #99 and https://github.com/FaithLife-Community/LogosLinuxInstaller/pull/99/commits/fc44b009f91366ec6e67a042c8b04b42bc8b5cd7
- [x] Create a tui_screen.TextScreen (see #99) that shows the list of required packages and show them being scanned/checked off when found, as a form of user feedback, during the dependency checking.
- [x] Add a status line. See #99.
  - When the TUI is running, we cannot see the CLI itself. We may want to consider making the TUI a full app, as in do not return to the CLI but keep the TUI open even on a blank screen, so as not to obscure output.
- [x] Add a progress bar. See #85.
- [x] Rework using curses.wrapper() for error handling. See https://github.com/FaithLife-Community/LogosLinuxInstaller/commit/818358897db2c8f1b95c47212226defc8952adc9.
- [x] Add a progress spinner/wheel to show that we are still working and not stalled. See #99.
- [x] Reduce number of screens by having multiple choices on one??? Probably too painful to generate nicely.
- [x] Implement doupdate instead of refresh

**Comment by thw26** [comment]
Some resources for the status line:

https://stackoverflow.com/questions/46011314/progress-bar-in-python-curses
https://stackoverflow.com/questions/13251299/creating-a-progress-bar-status-in-python-text-console
https://stackoverflow.com/questions/2122385/dynamic-terminal-printing-with-python

**Comment by thw26** [comment]
See also:

https://github.com/wong2/pick
https://github.com/anafvana/pickpack
