### ISSUE TITLE
AppImage handling

### ISSUE THREAD

**Issue by thw26** [FaithLife-Community/LogosLinuxInstaller#5]
In order to get to beta, we need to make sure our AppImage functionality is properly working as this is how we provide the most stable base install.

We want the new application to be able to download the latest AppImage from the repo, set the AppImage to a newly downloaded exe, or update the appimage in repo to the latest in our repository.

- [x] Convert checkAppImages(). See https://github.com/ferion11/LogosLinuxInstaller/pull/193/commits/bfefb3c05c7a9989e81372d77fa785fc75bd4e94
  - Another way to describe this would be: scan for additional AppImages (in Downloads only?) and add them to the binary list
- [x] Modify AppImage code to check branch version (see #32 and #38)
- [x] Fix set_appimage()
  - [x] This option should only be presented if the user installed using an AppImage. See #56.
  - [x] Update/Modify the config. See https://github.com/FaithLife-Community/LogosLinuxInstaller/pull/36.
  - [x] We should present our recommended AppImages from the FaithLife-Community repo. See https://github.com/FaithLife-Community/LogosLinuxInstaller/issues/5#issuecomment-1878014893. See #54.
  - [x] We should also present those downloaded by the user and which are available in their Logos APPDIR_BINDIR. See https://github.com/FaithLife-Community/LogosLinuxInstaller/pull/36.
- [ ] Add update_appimage()
  - This is similar to `set_appimage()` but bypasses the selection of any binary and simply updates to the latest installed if needed, sort of a quick action set_appimage().
  - [x] This option should only be presented if the user installed using an AppImage. See #56.
  - [ ] The user should be able to click a button or run a command to update to the latest recommended AppImage. See https://github.com/FaithLife-Community/LogosLinuxInstaller/issues/5#issuecomment-1909319121.
  - [x] This also will need the ability to check GitHub for new releases. See https://github.com/FaithLife-Community/LogosLinuxInstaller/issues/5#issuecomment-1878014893. See #54.
  - [x] Make app use the https://github.com/FaithLife-Community/wine-appimages repo. See https://github.com/FaithLife-Community/LogosLinuxInstaller/commit/1d7024a1a93ec07227b4952d1fda53dc15021b3f.
    - [x] Delete AppImage releases from this repo, but only after the above is done
- [x] Detect if AppImage Launcher is running, and, if so, prompt to disable it and warn that a reboot is necessary to proceed. See https://github.com/FaithLife-Community/LogosLinuxInstaller/issues/5#issuecomment-1878009808. See https://github.com/FaithLife-Community/LogosLinuxInstaller/pull/52.

We may want to have Logos launch and automatically check to see if there is a newer (recommended, as in, in repo) AppImage available.

**Comment by n8marti** [comment]
I haven't read through the whole list, but GH user @mmrtrt has several wine AppImages continuously released [here](https://github.com/mmtrt/WINE_AppImage/releases]. You might find something interesting or even useful in there.

**Comment by thw26** [comment]
> I haven't read through the whole list, but GH user @mmtrt has several wine AppImages continuously released [here](https://github.com/mmtrt/WINE_AppImage/releases). You might find something interesting or even useful in there.

This is the repo we download our AppImages from. The problem is there is no history, so we have to grab them before they're gone

**Comment by thw26** [comment]
One thing to note: AppImageLauncher (AIL), a popular piece of software that integrates AppImages with the host system, causes a conflict with the wine AppImage and renders the program broken. We need to detect if AIL is running, and if so, prompt to disable it. This further requires a system reboot (or perhaps just logging back in) to remove the conflicting changes.

Manjaro enables AIL by default, for instance. There was some code I wrote in the commit linked above that attempted to account for AIL before realizing that AIL itself broke the wine AppImage.

**Comment by thw26** [comment]
We either need to figure out how to grab something like an RSS feed for our AppImage releases on GitHub (and extract the URL for the download) or we need to store a list of our AppImages in a file in our Python app containing the URLs for quick reference. I'd prefer the RSS route as it would automated, but the URLs would be easy enough to update.

**Comment by n8marti** [comment]
GitHub has a very useful API, so we should fairly easily be able to filter out what we need using something like:
```python
>>> import requests
>>> url = 'https://api.github.com/repos/FaithLife-Community/LogosLinuxInstaller/releases'
>>> r = requests.get(url)
>>> print(r.json()[0].get('assets')[0].get('browser_download_url'))
https://github.com/FaithLife-Community/LogosLinuxInstaller/releases/download/v4.0.0-alpha.1/LogosLinuxInstaller
```

**Comment by n8marti** [comment]
by the way, that's also where we can see some other interesting stats:
```python
>>> import requests
>>> url = 'https://api.github.com/repos/FaithLife-Community/LogosLinuxInstaller/releases'
>>> r = requests.get(url)
>>> print(r.json()[0].get('assets')[0].get('browser_download_url'))
https://github.com/FaithLife-Community/LogosLinuxInstaller/releases/download/v4.0.0-alpha.1/LogosLinuxInstaller
>>> print(r.json()[0].get('assets')[0].get('name'))
LogosLinuxInstaller
>>> print(r.json()[0].get('assets')[0].get('size'))
27695128
>>> print(r.json()[0].get('assets')[0].get('download_count'))
6
```

**Comment by thw26** [comment]
Now that we can find the branch version, we just need to modify the appimage handling code to do so.

Would it still be beneficial to keep our repos separate and make use of the API as such?

I like being able to get stats on actual number of users. We could run the same for the Ferion11 repo since that will have much more historical data.

I will modify the checklist in the OP.

**Comment by thw26** [comment]
There is a new community repo here:

https://github.com/FaithLife-Community/wine-appimages/releases

We should use this when attempting to fix the get AppImages from GitHub TODO and the update-to-latest GitHub AppImage.

It would be neat if the GUI could present some kind of highlighting or exclamation mark to the user on such an update command, running the check for a new version in the background.
